# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: huang-x-h.github.io
email: huang.x.hui@gmail.com
description: >
  Personal blog about programming.
logo: "/assets/images/gravatar.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huang-x-h.github.io" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'huang.xinghui'
bio: >
  Programmer
author_image: "/assets/images/gravatar.jpg"
twitter_username: huangxinghui
github_username:  huang-x-h

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-paginate
