paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
markdown: kramdown
kramdown:
  input: GFM
pygments: true
permalink: /blog/:year/:month/:day/:title

title: Personal Blog
description: Personal Blog
author:
  name: dormouse
  email: huang.x.hui@gmail.com
  github: huang-x-h
  weibo: 1749887314
  bio: Programmer

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
baseurl: http://huang-x-h.github.io