markdown: kramdown
kramdown:
  input: GFM
permalink: /blog/:year/:month/:day/:title/

title: huang-x-h.github.io
description: "Personal blog about programming"
author:
  name: huang.xinghui
  email: huang.x.hui@gmail.com
  github: huang-x-h
  weibo: 1749887314
  bio: Programmer
excerpt_separator: "<!-- more -->"

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html